title: FÃ©lix Desmeules-Trudel
author: GitHub User
email: fdesm014@uottawa.ca
description: Ph.D. Candidate in the Department of Linguistics - uOttawa
github_username:  felixdtrudel

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
